transport-xmpp: Avoid deadlock
There (hopefully) was a deadlock when the connection was unclean
shutdown, e.g.:

08-17 09:46:56.520 D/MAXS/XMPPTCPConnection(30189): PacketWriter shutdown()
08-17 09:46:56.523 D/MAXS/XMPPTCPConnection$PacketWriter(30189): Reporting shutdownDone success in writer thread
08-17 09:46:56.524 D/MAXS/XMPPTCPConnection(30189): PacketWriter has been shut down
08-17 09:46:56.524 D/MAXS/XMPPTCPConnection(30189): PacketReader shutdown()
08-17 09:46:56.525 D/MAXS/XMPPTCPConnection(30189): PacketReader has been shut down
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189): Connection XMPPTCPConnection[flo-motog4@geekplace.eu/MAXS] (0) closed with error ja
vax.net.ssl.SSLException: Read error: ssl=0x95125480: I/O error during system call, Connection timed out
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocket
Impl.java:758)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.io.InputStreamReader.read(InputStreamReader.java:184)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.io.BufferedReader.read1(BufferedReader.java:221)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.io.BufferedReader.read(BufferedReader.java:297)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:42)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1535)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:1007)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.kxml2.io.KXmlParser.next(KXmlParser.java:357)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPC
onnection.java:982)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnec
tion.java:998)
08-17 09:46:56.553 W/MAXS/AbstractXMPPConnection(30189):    at java.lang.Thread.run(Thread.java:761)
08-17 09:46:56.559 D/MAXS/JulDebugger(30189): XMPPConnection closed due to an exception (XMPPTCPConnection[flo-motog4@geekplace.eu/MAXS] (0)
) (javax.net.ssl.SSLException: Read error: ssl=0x95125480: I/O error during system call, Connection timed out)
08-17 09:46:56.560 W/MAXS/HandleConnectionListener(30189): connectionClosedOnError
08-17 09:46:56.560 D/MAXS/XMPPService(30189): changeState: mState=Connected, desiredState=InstantDisconnected

which looked in the thread dump like this:

"MAXSTransportService[XMPP]" prio=5 tid=12 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x2ac055e0 self=0xada86800
  | sysTid=30205 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0x95ed5920
  | state=S schedstat=( 4030104929 6460640979 9681 ) utm=309 stm=93 core=5 HZ=100
  | stack=0x95dd3000-0x95dd5000 stackSize=1038KB
  | held mutexes=
  at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:369)
  - waiting to lock <0x0aa50967> (a org.jivesoftware.smack.tcp.XMPPTCPConnection) held by thread 22
  at org.projectmaxs.transport.xmpp.xmppservice.XMPPService.tryToConnect(XMPPService.java:715)
  - locked <0x0bfa30c6> (a org.projectmaxs.transport.xmpp.xmppservice.XMPPService)
  at org.projectmaxs.transport.xmpp.xmppservice.XMPPService.changeState(XMPPService.java:590)
  - locked <0x0bfa30c6> (a org.projectmaxs.transport.xmpp.xmppservice.XMPPService)
  at org.projectmaxs.transport.xmpp.xmppservice.XMPPService.connect(XMPPService.java:245)
  at org.projectmaxs.transport.xmpp.TransportService.onHandleIntent(TransportService.java:122)
  at org.projectmaxs.shared.transport.MAXSTransportService$ServiceHandler.handleMessage(MAXSTransportService.java:72)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)

"Smack Packet Reader (0)" daemon prio=5 tid=22 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x2ad93f70 self=0xa2112900
  | sysTid=14569 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0x9477f920
  | state=S schedstat=( 574132040 209066455 269 ) utm=55 stm=1 core=4 HZ=100
  | stack=0x9467d000-0x9467f000 stackSize=1038KB
  | held mutexes=
  at org.projectmaxs.transport.xmpp.xmppservice.XMPPService.changeState(XMPPService.java:565)
  - waiting to lock <0x0bfa30c6> (a org.projectmaxs.transport.xmpp.xmppservice.XMPPService) held by thread 12
  at org.projectmaxs.transport.xmpp.xmppservice.XMPPService.instantDisconnect(XMPPService.java:253)
  at org.projectmaxs.transport.xmpp.xmppservice.HandleConnectionListener$1.connectionClosedOnError(HandleConnectionListener.java:48)
  at org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener(AbstractXMPPConnection.java:1300)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection.notifyConnectionError(XMPPTCPConnection.java:913)
  - locked <0x0aa50967> (a org.jivesoftware.smack.tcp.XMPPTCPConnection)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$3200(XMPPTCPConnection.java:150)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
  at java.lang.Thread.run(Thread.java:761)

Hopefully removing the call to instantDisconnect() in
HandleConnectionListener will fix this. The call is not necessary as
Smack will call instantDisconnect() prior calling
connectionClosedOnError(Exception) anyways.