module-smssend: Fix NPE if (sent|delivery)Intents is null
It seems that the API contract is violated on some Android devices.

Example user error report:

java.lang.NullPointerException: collection == null
  at android.os.Parcel.readException(Parcel.java:1437)
  at android.os.Parcel.readException(Parcel.java:1385)
  at com.android.internal.telephony.ISms$Stub$Proxy.sendMultipartText(ISms.java:631)
  at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:214)
  at org.projectmaxs.module.smssend.commands.AbstractSmsSendCommand.sendSms(AbstractSmsSendCommand.java:105)
  at org.projectmaxs.module.smssend.commands.ReplyTo.execute(ReplyTo.java:66)
  at org.projectmaxs.shared.module.MAXSModuleIntentService.onHandleIntent(MAXSModuleIntentService.java:168)
  at org.projectmaxs.shared.module.MAXSModuleIntentService$ServiceHandler.handleMessage(MAXSModuleIntentService.java:71)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
  at android.os.HandlerThread.run(HandlerThread.java:61)

Android 4.3.1 (Cyanogen Mod)
Samsung GT-I9100
MAXS: 1.0.0.0 (0.0.1.18-39-g06f1de8 2014-10-24)